// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvmofgcvzhuvfysuadhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2bW9mZ2N2emh1dmZ5c3VhZGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTM0MDUsImV4cCI6MjA2NzI4OTQwNX0.L8pbD8F-5GgviV947YPHwPUYaSNbtHiB1G7KbuRNzJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});